apiVersion: lifecycle.keptn.sh/v1
kind: KeptnTaskDefinition
metadata:
  name: url-test-runner
  namespace: default
spec:
  container:
    name: testkube-runner
    image: kubeshop/testkube-cli:latest
    command:
      - 'sh'
      - '-c'
      - |
        testkube set context --org-id <org-id> --env-id <env-id> -c cloud -k <api-key>
        testkube run tw curl-sample
